### ISSUE TITLE
Characters are displayed in a strange order

### ISSUE THREAD

**Issue by levitas23** [MaddoScientisto/LostWordTracker#7]
Ideally the characters would be shown in an order that can be forced by the game - such as "universe" order or something by default.  As is, it is difficult to enter data for multiple characters.  (delete if duplicate for the character sorting issue)

**Comment by MaddoScientisto** [comment]
Yes, that strange order is the order I inserted them in the database, I still haven't decided on a proper default order since there's no public official order in the game itself, I suppose that the sorting options like the game has (level, rarity, etc) and tier could be implemented, I'll close this one since the sorting issue will take care of it
